<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>


  <parent>
    <groupId>org.frankframework</groupId>
    <artifactId>multi-module-template</artifactId>
    <version>${revision}</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>frontend</artifactId>
  <version>${revision}</version>

  <properties>
    <frontend.dist.dir>${project.basedir}/dist/browser</frontend.dist.dir>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.5.1</version>
        <executions>
          <execution>
            <id>pnpm install</id>
            <goals>
              <goal>exec</goal>
            </goals>
            <phase>prepare-package</phase>
            <configuration>
              <executable>pnpm</executable>
              <arguments>
                <argument>i</argument>
                <argument>--frozen-lockfile</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>pnpm build</id>
            <goals>
              <goal>exec</goal>
            </goals>
            <phase>prepare-package</phase>
            <configuration>
              <executable>pnpm</executable>
              <arguments>
                <argument>run</argument>
                <argument>build</argument>
                <argument>--base-href</argument>
                <argument>/frontend/</argument>
              </arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.4.2</version>
        <executions>
          <execution>
            <id>package-frontend-dist</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <classesDirectory>${frontend.dist.dir}</classesDirectory>
              <includes>
                <include>**/*</include>
              </includes>
              <classifier>dist</classifier>
            </configuration>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>

</project>
