# Docker compose to start and build the webapp service. For a full build, use Maven.

services:
  webapp:
    image: ghcr.io/frankframework/webapp-template:latest
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    ports:
      - "8080:8080"